version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: unless-stopped
    # Eliminamos 'ports' para obligar a que todo pase por Traefik (seguridad)
    volumes:
      # --- CÓDIGO (Desde tu Git) ---
      # Mapeamos solo temas y plugins para que se actualicen con tu repo
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      
      # --- DATOS (Persistencia en el Servidor) ---
      # Usamos un volumen nombrado para las imágenes subidas. 
      # Esto evita que Git toque tus fotos y facilita los backups.
      - uploads_data:/var/www/html/wp-content/uploads
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      
    networks:
      - internal
      - dokploy-network
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    labels:
      - "traefik.enable=true"
      # Usamos solo la variable. Asegúrate de definir DOMAIN_NAME en Dokploy.
      - "traefik.http.routers.mienteme-router.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.mienteme-router.entrypoints=websecure"
      - "traefik.http.routers.mienteme-router.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mienteme-router.service=mienteme-svc"
      - "traefik.http.services.mienteme-svc.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"

volumes:
  db_data:
  uploads_data: # Volumen nuevo para separar las subidas del código

networks:
  internal:
    driver: bridge
  dokploy-network:
    external: true